title: Standard Sats
description: Lightning-native synthetic assets
baseurl: ""
url: "https://standardsats.github.io"

logo: /assets/img/logo.png
apkpic: /assets/img/apk_pic.png
show_downloads: false
github_username: standardsats

# project links:
chat: https://t.me/StandardSatsCommunity
eclair: https://github.com/ACINQ/eclair
plugin: https://github.com/standardsats/plugin-fiat-channels
wallet: https://github.com/standardsats/wallet
wallet_eur_release: https://github.com/standardsats/wallet/releases/tag/3.0.0
rfc: https://github.com/standardsats/fiat-channels-rfc

telegram: https://t.me/StandardSatsCommunity

show_excerpts: false # set to false to remove excerpts on the homepage
# theme: jekyll-theme-minimal
remote_theme: pages-themes/minimal@v0.2.0
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
plugins:
  - jekyll-theme-minimal
  - jekyll-redirect-from
  - jekyll-remote-theme
whitelist:
  - jekyll-theme-minimal
  - jekyll-redirect-from
