title: Standard Sats Project
description: Lightning-native synthetic assets

logo: /assets/img/logo.png
show_downloads: false
github_username: standardsats

# project links:
eclair: https://github.com/ACINQ/eclair
plugin: https://github.com/standardsats/plugin-fiat-channels
wallet: https://github.com/standardsats/wallet
rfc: https://github.com/standardsats/fiat-channels-rfc

telegram:
contact:
twitter:

show_excerpts: false # set to false to remove excerpts on the homepage
theme: jekyll-theme-minimal
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
plugins:
  - jekyll-theme-minimal
  - jekyll-redirect-from
whitelist:
  - jekyll-theme-minimal
  - jekyll-redirect-from
